articles/urls.py
from django.urls import path
from .views import (ArticleCreateView,ArticleListView,ArticleUpdateView,ArticleDeleteView, CustomLoginView,CustomListView,UserRegistration,contact_form_view,user_update_profile_view,article_detail, list_article_view,UserArticleView,likeview
)
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,

)
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

app_name = 'articles'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='articles:article-list'), name='logout'),
    path('register/',UserRegistration.as_view(),name='register'),
    path('',ArticleListView.as_view(), name='article-list'),
    path('user/<str:username>',UserArticleView.as_view(), name='user-article-list'),
    path('articles/tag/<slug:tag_slug>/',list_article_view, name='article-tag-list'),
    path('article/<int:pk>/detail/',article_detail, name='article-detail'),
    path('article/create/',ArticleCreateView.as_view(), name='article-create'),
    path('article/<int:pk>/update/',ArticleUpdateView.as_view(), name='article-update'),
    path('article/<int:pk>/delete/',ArticleDeleteView.as_view(), name='article-delete'),
    path('articles/edit',CustomListView.as_view(), name='article-cutomize'),
    path('profile/<int:pk>/update/', user_update_profile_view, name='update-view'),
    path('like/<int:pk>',likeview, name='article-like'),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings
from articles.views import contact_form_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('articles.urls')),
    path('about/',contact_form_view, name='about-view'),
        path('password-reset/', auth_views.PasswordResetView.as_view(template_name='articles/password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='articles/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='articles/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='articles/password_reset_complete.html'), name='password_reset_complete'),
]


#  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) it is for cdn(for development)

articles/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from PIL import Image
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField

# Create your models here.



class Article(models.Model):

    user        = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title         = models.CharField(max_length=300)
    # content       = models.TextField()
    content       = RichTextField(blank=True, null=True)
    released_date = models.DateField('date published',auto_now_add=True)
    tags       = TaggableManager()
    likes   = models.ManyToManyField(User,related_name='blog_article')

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return f'{self.title}   |   {str(self.user)}'

    class Meta:
        ordering = ['-released_date']

    def get_absolute_url(self):
        return reverse('articles:article-detail', kwargs={'pk':self.pk})


class Profile(models.Model):

    _user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default='default-profile.jpg')

    def __str__(self):
        return f'{self._user.username} profile picture'



class Comment(models.Model):

    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    name    = models.CharField(max_length=80)
    email   = models.EmailField(null=True,blank=True)
    body    = models.TextField()
    created = models.DateField(auto_now_add=True)
    active  = models.BooleanField(default=True)
    

    def __str__(self):
        return f'{self.name}\'s comment on {self.article}'

    class Meta:
        ordering = ['-created']

articles/forms.py
from django.forms import widgets
from .models import Article,Profile,Comment
from django.contrib.auth.models import User 
from django import forms
from django.contrib.auth.forms import UserCreationForm 


class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model  = Article
        fields = '__all__'
        exclude = ['user','likes']

        widgets = {
            'content':forms.Textarea(attrs={'placeholder':'You can use markdown syntax here'})
        }
class UserRegistrationform(UserCreationForm):
    email = forms.EmailField()
    # first_name = forms.CharField(max_length=100)
    # last_name = forms.CharField(max_length=100)
    # profile_image     = forms.ImageField(required=False)
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

class UpdateProfileForm(forms.ModelForm):
    email = forms.EmailField(required=False)
    class Meta:
        model = User
        fields = ['username','email']


 
class UpdateProfilePic(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_pic']



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

articles/views.py
from django.contrib.auth.models import User
from django.db.models import Count
from django.http import request
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render,redirect
from django.urls import reverse
from .models import Article, Profile,User,Comment
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    CreateView,
    DeleteView,
)
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
from django.views.generic.edit import FormView
from django.contrib import messages
from .forms import (ArticleCreateForm,
        UserRegistrationform,
        UpdateProfileForm,
        UpdateProfilePic,
        CommentForm,
)
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin ,UserPassesTestMixin
from django.contrib.auth import login
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required 
from taggit.models import Tag



def likeview(request, pk):
    article = get_object_or_404(Article,id=request.POST.get('article_id'))   
    liked = False
    if article.likes.filter(id=request.user.id).exists():
        article.likes.remove(request.user)
        liked=False
    else:
        article.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('articles:article-detail',args=[str(pk)]))

#if you want to add unlike button
# def unlikeview(request, pk):
#     article = get_object_or_404(Article,id=request.POST.get('article_id'))
#     article.likes.remove(request.user)
#     return HttpResponseRedirect(reverse('articles:article-detail',args=[str(pk)]))



class CustomLoginView(LoginView):
    template_name = 'articles/login_view.html'
    fields = '__all__'
    redirect_authenticated_user = True   #this will prevent logged in users to go to login page.
 
    def get_success_url(self):
        return reverse('articles:article-list')

 

class UserRegistration(FormView):
    template_name = 'articles/register.html'
    form_class = UserRegistrationform
    
    def get_success_url(self):
        return reverse('articles:article-list')
    #this method will override the get method of the Formview and will restrict users logged in from going to register page simply just by redirect.

    # redirect_authenticated_user = True
    # in here redirect_authenticated_user is not a property or attr so we create one for this.
    def get(self,*args,**kwargs):  
        if self.request.user.is_authenticated:
            return redirect('articles:article-list')
        return super(UserRegistration, self).get(self,*args,**kwargs)#this line means in other situation go for what you supposed to do.
    # POST method for recieving form
    def form_valid(self,form):
        user = form.save()

        if user is not None:
            login(self.request, user)   #this login method will login the user right after pressing submit button.
        return super(UserRegistration,self).form_valid(form)



class ArticleListView(ListView):
    template_name  = 'articles/article_list.html'
    paginate_by = 8

    def get_queryset(self):
        search_input  = self.request.GET.get('search-area')
        if search_input:
            return Article.objects.filter(title__contains=search_input )
        else:
            return Article.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        # search_input = self.request.GET.get('search-area') or ''
        # if search_input:
        #     context['object_list'] = context['object_list'].filter(
        #         title__icontains=search_input)
        # context['search_input'] = search_input
    
        context['user_pic'] = Profile.objects.filter(_user__id = self.request.user.id).first()
        return context


class UserArticleView(ListView):
    template_name  = 'articles/specific_user_articles_list.html'
    queryset       = Article.objects.all()
    paginate_by    = 5
    
    def get_queryset(self):
        user = get_object_or_404(User,username=self.kwargs.get('username'))
        return Article.objects.filter(user=user)
    
    

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['object_list'] = context['object_list'].filter(
                title__icontains=search_input)
        context['search_input'] = search_input
        context['user_pic'] = Profile.objects.filter(_user__id = self.request.user.id).first()
        return context

# list post view by tag
def list_article_view(request, tag_slug= None):
    object_list = Article.objects.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug =tag_slug)
        object_list = object_list.filter(tags__in=[tag])


    paginator = Paginator(object_list,5)
    page      = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        articles = paginator.page(1)

    return render(request, 'articles/tag_list.html', {'object_list': object_list, 'page':page,'articles':articles ,'tag':tag})




class ArticleCreateView(LoginRequiredMixin,CreateView):
    template_name ='articles/article_create.html'
    form_class = ArticleCreateForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleCreateView,self).form_valid(form) 

    def get_success_url(self):
        return reverse('articles:article-cutomize')

class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin ,UpdateView):
    form_class = ArticleCreateForm
    template_name ='articles/article_update.html'
    queryset = Article.objects.all()

    def test_func(self):
        article = self.get_object()
        if self.request.user == article.user:
            return True
        return False

def article_detail(request,  pk):

    article = get_object_or_404(Article, pk = pk)
    comments = article.comments.filter(active=True)

    if request.method == 'POST':
        form = CommentForm(request.POST or None)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.article = article
            new_comment.name = request.user.username
            new_comment.email = request.user.email
            new_comment.save()
            messages.success(request,message='Your comment has been added successfuly.')
            #when comment has been sent the form will be empty. 
            form = CommentForm()  
    # i used the user information to Initialize the name and email of the form.so we won't need this.
    
    # if request.user.is_authenticated:
    #     # initial = {'name':request.user.username,'email':request.user.email}
    #     form = CommentForm(initial=initial)  
    
    else:
        form = CommentForm()
    liked = False
    if article.likes.filter(id=request.user.id):
        liked = True
    article_tags_ids = article.tags.values_list('id',flat=True)
    similar_posts    = Article.objects.filter(tags__in=article_tags_ids).exclude(id=article.id)
    similar_posts    = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-released_date')
    return render(request,'articles/article_detail.html' , {'article':article,
    'comments':comments,
    'form': form,
    'similar_posts': similar_posts,
    'liked': liked
    })




class ArticleDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    template_name = 'articles/article_delete.html'
    queryset = Article.objects.all()

    def get_success_url(self):
        return reverse('articles:article-cutomize')

    
    def test_func(self):
        article = self.get_object()
        if self.request.user == article.user:
            return True
        return False


    

class CustomListView(LoginRequiredMixin,ListView):
    model = Article
    template_name = 'articles/edit_article_list.html'
    paginate_by   = 6
    
    def get_queryset(self):
        return Article.objects.filter(user=self.request.user)
 

  
#function view for contact page.
def contact_form_view(request,*args, **kwargs):
    if request.method == 'POST':
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message_content = request.POST['message-content']

        send_mail(
            message_name,
            message_content,
            message_email,
            ['prgm.pouya19@gmail.com']
        )
        return render(request, 'about.html',{'message_name':message_name})
    else:
        return render(request, 'about.html', {})


#function view for updating profile
def user_update_profile_view(request, *args, **kwargs):

    if request.method == 'POST': 
        u_form = UpdateProfileForm(request.POST,instance=request.user)
        p_form = UpdateProfilePic(request.POST,request.FILES,instance= request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,f'your acount has been updated!')
            return redirect( 'articles:update-view', pk=request.user.pk) 
        else:
            messages.success(request, f'There was an error in your form...')
            u_form = UpdateProfileForm(instance=request.user)
            p_form = UpdateProfilePic(instance= request.user.profile)
            # p_form = UpdateProfilePic(instance= Profile.objects.get(_user__id = request.user.id))
            return redirect( 'articles:update-view', id=request.user.id) 
        #always for submitting data over form use redirect,because if you use render it will popup a window says 'are you sure you want to reload cause the '


    u_form = UpdateProfileForm(instance=request.user)

articles/templates/articles/article_detail.html
{% extends 'layout.html' %}{% load crispy_forms_tags %}{% load article_tags %} {% block title %}
<title>Detail</title>
{% endblock %}{% block jumbotron %}{% endblock %}{% block content %}
<div class="text-center">
  <h1 class="text-capitalize text-info">{{ article.title }}</h1>
  <small
    class="text-muted">by <a href="{% url 'articles:user-article-list' article.user.username %}">
      {{ article.user.username }}</a> | {{article.released_date|date:"d,M,Y"}}</small
  >
  
</div>
<br />

{% if messages %}
{% for message in messages %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  {% endfor %}
  {% endif %}
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-9 col-sm-12">
    
      <p class="text-justify  ">{{ article.content|markdown }}</p>
      <br>
      <!-- like form  -->
      {% if user.is_authenticated %}
        
          <form action="{% url 'articles:article-like' article.pk %}" method="POST" class="d-inline">
            {% csrf_token %}
            {% if liked %}
            <button type="submit" name="article_id" value={{article.id}} class="btn btn-danger btn-sm">
              UnLike
            </button>
            {% else %}
            <button type="submit" name="article_id" value={{article.id}} class="btn btn-primary btn-sm">
              Like
            </button>
            {% endif %}
            - {{article.total_likes}} like{{article.total_likes|pluralize:'s'}}
          </form>
      {% else %}
      <a href="{% url 'articles:login' %}">Login</a> to like - {{article.total_likes}} like{{article.total_likes|pluralize:'s'}}
      {% endif %}
      <br>
      <!-- tags -->
      <small>Tags: {% for tag in article.tags.all %}<a href="{% url 'articles:article-tag-list' tag.slug %}">
        {{ tag }}{% if not forloop.last %},{% endif %}</a>{% empty %}no tag specified{% endfor %}</small><br>
        <small class="bg-light">also see articles by <a href="{% url 'articles:user-article-list' article.user.username %}">
          {{ article.user.username }}
          </a></small>
        <hr>
    </div>
        <!-- similar articles -->
    <div class="col-lg-3 col-sm-12 my-2">
      <h3 class="border-bottom">Similar articles</h3>
      {% for article in similar_posts %}
        <ul class="m-0">
          <li><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></li>
        </ul>
      {% empty %}
      <small class="text-dark" >There is no similar articles yet.</small>
      {% endfor %}
    </div>
  {% if comments %}
  <br><br>
  <div class="comments col-sm-12 col-lg-10">
      <p>{{ comments|length }} comment{{comments|pluralize:'s'}} on this post.</p>
      {% for comment in comments %}
      <div class="card text-muted bg-light mt-2 w-75">
        <div class="card-body p-2">
          <small class="card-subtitle p-0">{{comment.name}} - {{comment.created|date:"d,M,Y"}}</small>
          <hr class="m-0">
          <p class="card-text">{{comment.body|linebreaks}}</p>
        </div>
      </div> 
      {% endfor %}
  </div>
   {% else %}
   <p class="ml-3">No comments yet. </p>
   {% endif %}

   <br><br><br>
   {% if user.is_authenticated %}
  <div class="my-5 col-sm-12">
     <h4 class="border-bottom mb-4">comment on this post</h4>
     <form method="POST" class="w-50">
       {% csrf_token %}
       {{form|crispy}}
       <input type="submit" class="btn btn-primary" value="submit">
     </form>
  </div>
   {% else %}
   <h3 class="text-muted text-center m-5">Only registered users can post comments, please <a href="{% url 'articles:login' %}?next={{request.path}}">Login</a></h3>
   {% endif %}
</div>
{% endblock %}


<!-- A tiny note: as you can see if i wanna to link to update page i have to get primary_key(pk) -->

articles/templates/articles/article_list.html
{% extends 'layout.html' %} {% load static %} {% load article_tags %}{% block title %}
<title>The website articles</title>
{% endblock %}{% block content %}

<style>
  .card {
  min-height: 5rem;
}
.col-md-2 img {
  width: 90%;
}
.linked-card {
  color: #000;
}
.linked-card:hover {
  text-decoration: none;
}
.footer{
  clear: both;
  position: relative;
  height: 150px;
}
@media only screen and (max-width: 768px) {
  .card {
    min-height: 5rem;
  }
  .col-md-2 img {
    width: 10%;
  }
  .btn {
    margin-top: 1rem;
  }
}
</style>
<div class="row">
  <div class="col-md-8 col-sm-12">
    {% for instance in object_list %}

      <!-- card box -->
      <div class="card mt-3 shadow">
        <div class="row text-wrap overflow-hidden text-justify p-3">
          <div class="col-md-2">
            
            <img
              src="{{ instance.user.profile.profile_pic.url }}"
              alt="profile picture"
              class="rounded-circle img-fluid"
            />

          </div>
          <div class="col-md-10">
            <a
            href="{% url 'articles:article-detail' pk=instance.pk %}"
            class="linked-card"
          >
            <h4 id="title" class="card-title m-0 text-capitalize">
              {{instance.title}}
            </h4>
          </a>
            <small id="sub-title" class="card-subtitle text-muted">
              by <a href="{% url 'articles:user-article-list' instance.user.username %}">{{instance.user}}</a> | {{instance.released_date|date:'d,M,Y'}}
            </small>
            <p id="content" class="card-text mb-0">
              {{  instance.content|markdown|truncatewords_html:30 }}
            </p>
            <span class="bg-warning">{{ instance.total_likes }} - like{{instance.total_likes|pluralize:'s'}}</span>
            {% if instance.tags.all %}
            <p class="text-secondary">Tags: {% for tag in instance.tags.all %}
                <a href="{% url 'articles:article-tag-list' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %},{% endif %}{% endfor %}
            </p>
            {% endif %}
          </div>
        </div>
      </div>
    
    {% endfor %}
    {% include 'pagination.html' with page=page_obj %}
  </div>

  <!-- search form -->
  <div class="col-md-4 col-sm-12 mt-3">
    <form action="." method="GET" name="form" id="form" class="form-inline mb-2">
      <label for="search_inp">Search articles by title:</label>
      <input
        type="text"
        name="search-area"
        id="search_inp"
        value="{{search_input}}"
        class="form-control"
      />
      <input
        type="submit"
        id="search"
        value="search"
        class="btn btn-secondary ml-1 form-control"
      />
    </form>
    {% get_latest_articles 5 %}
    <span>
      Create your post?
      <a
        href="{% if request.user.is_authenticated %}{% url 'articles:article-create' %}{% else %}{% url 'articles:login' %}{% endif %}"
        >click here</a
      ></span
    >

  </div>
  
</div>
<div class="footer container">
  <hr />
  <h6 class="text-success d-inline">Social Media:</h6>
  <a
    href="https://www.linkedin.com/in/pouya-pargam-1917b6218"
    class="fa fa-linkedin"
  ></a>
  <a href="https://www.instagram.com/pouyap19" class="fa fa-instagram"></a>
  <a href="{% url 'about-view' %}" class="d-block float-right">About this website</a><br>
  <a href="{% url 'about-view' %}" class="d-block float-right">Contact me</a>
  <p class="text-center ">copyright<span class="fa fa-copyright" aria-hidden="true"></span>{% now 'Y' %}</p>

    

</div>

{% endblock %}

articles/templates/articles/edit_article_list.html
{% extends 'layout.html' %}{% load static %}{% load article_tags %}{% block title %}
<title>Your posts</title>
{% endblock %}{% block jumbotron %}{% endblock %} {% block content %}
<h3>Hi {{request.user|title}}</h3>
<h5>Edit your posts here...</h5>

<!-- get first image in the user Article model -->
<!-- because i didn't separate the model Article in each article the default image will be set -->
<div class="row">
  <div class="col-md-8 mb-5 col-sm-12">
    {% if object_list %} {% for obj in object_list %}
    <div class="card mt-2 shadow-sm h-auto">
      <div class="card-body">
        <h6 class="card-title text-capitalize">{{ obj.title }}</h6>
        <p class="card-content">
          {{ obj.content|markdown|truncatewords_html:50 }}... .<a
            href="{% url 'articles:article-detail' pk=obj.pk %}"
            >see more</a
          >
        </p>
        <div class="card-link">
          <a
            href="{% url 'articles:article-delete' pk=obj.pk %}"
            class="btn btn-danger btn-sm"
            >Delete</a
          >
          <a
            href="{% url 'articles:article-update' pk=obj.pk %}"
            class="btn btn-info btn-sm"
            >Edit</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
    {% include 'pagination.html' with page=page_obj %}
  </div>

  <div class="col-md-4 col-sm-12 mb-4">
    <a href="{% url 'articles:article-create' %}">Create another post?</a>
    {% get_latest_articles 5 %}
  </div>
</div>
{% else %}
<div class="m-5">
  <h3 class="text-danger">No items yet</h3>
  <a href="{% url 'articles:article-create' %}"
    >Click to Write your first article</a
  >
</div>

{% endif %} {% endblock %}

articles/templates/articles/latest_artilce_list.html
<hr>
<h6>Latest Articles:</h6>
<ul>
    {% for article in latest_articles %}
    <li> <a href="{{ article.get_absolute_url }}">{{ article.title }}
 </li></a>
 {% endfor %}
</ul>
<hr>

articles/templates/articles/login_view.html
{% extends 'layout.html' %}{% load crispy_forms_tags %}{% block title %}
<title>Login</title>
{% endblock %}{% block jumbotron %}{% endblock %}{% block content %}
<style>
    @media only screen and (max-width: 600px) {
    .register-box {
        width: 75%;
    }
}
    @media only screen and (min-width: 600px) {
    .register-box {
        width: 50%;
    }
}
</style>
<div class="register-box p-2">
    <fieldset class="form-group">
        <legend class="mb-2 border-bottom">Log in</legend>
        <form action="." method="POST" class="mb-2">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Login" class="btn btn-success"></input>
            <small class="text-muted ml-2"><a href="{% url 'password_reset' %}">forgot your password?</a></small>
        </form> 
        <small class="text-muted border-top" >You didn't signed up yet? <a href="{% url 'articles:register' %}">Register</a></small>
    </fieldset>
</div>


{% endblock %}

articles/templates/articles/password_reset_complete.html
{% extends 'layout.html' %}{% load crispy_forms_tags %}{% block title %}
<title>Login</title>
{% endblock %}{% block jumbotron %}{% endblock %}{% block content %}

<div class="alert alert-info w-50">
    your password has been changed successfully.
</div>
<a href="{% url 'articles:login' %}">Sign in here</a>


{% endblock %}

articles/templates/articles/tag_list.html
{% extends 'layout.html' %} {% load static %}{% load article_tags %} {% block title %}
<title>The website articles</title>
{% endblock %}{% block content %}

<style>
  .card {
  min-height: 10rem;
}
.col-md-2 img {
  width: 90%;
}
.linked-card {
  color: #000;
}
.linked-card:hover {
  text-decoration: none;
}
.footer{
  clear: both;
  position: relative;
  height: 150px;
}
@media only screen and (max-width: 768px) {
  .card {
    min-height: 10rem;
  }
  .col-md-2 img {
    width: 10%;
  }
  .btn {
    margin-top: 1rem;
  }
}
</style>
<div class="row">
  <div class="col-md-8">
      {% if tag %}
      <h2>articles tagged with {{ tag.name }}</h2>
      {% endif %}
    {% for instance in object_list %}
 
      <div class="card mt-3 shadow">
        <div class="row text-wrap overflow-hidden text-justify p-3">
          <div class="col-md-2">
            
            <img
              src="{{ instance.user.profile.profile_pic.url }}"
              alt="profile picture"
              class="rounded-circle img-fluid"
            />

          </div>
          <div class="col-md-10">
            <a
            href="{% url 'articles:article-detail' pk=instance.pk %}"
            class="linked-card"
          >
            <h4 id="title" class="card-title m-0 text-capitalize">
              {{instance.title}}
            </h4>
        </a>
            <small id="sub-title" class="card-subtitle text-muted">
              by <a href="{% url 'articles:user-article-list' instance.user.username %}">{{instance.user}}</a> | {{instance.released_date|date:'d,M,Y'}}
            </small>
            <p id="content" class="card-text mb-0">
              {{instance.content|slice:':130'|safe}} ...
            </p>
            <p class="text-secondary">Tags: {% for tag in instance.tags.all %}
                <a href="{% url 'articles:article-tag-list' tag.slug %}">{{ tag.name }}</a>
               {% if not forloop.last %},{% endif %}{% endfor %}
            </p>
          </div>
        </div>
      </div>
      {% endfor %}
      {% include 'pagination.html' with page=articles %}
  </div>

  <!-- side bar -->
  <div class="col-md-4 mt-5">
    {% get_latest_articles 5 %} 
    <br />
    Create your post?<span>
      <a
        href="{% if request.user.is_authenticated %}{% url 'articles:article-create' %}{% else %}{% url 'articles:login' %}{% endif %}"
        >click here</a
      ></span
    >
 
  </div>

</div>
<div class="footer container">
  <hr />
  <h6 class="text-success d-inline">Social Media:</h6>
  <a
    href="https://www.linkedin.com/in/pouya-pargam-1917b6218"
    class="fa fa-linkedin"
  ></a>
  <a href="https://www.instagram.com/pouyap19" class="fa fa-instagram"></a>
  <a href="{% url 'about-view' %}" class="d-block float-right">About this website</a><br>
  <a href="{% url 'about-view' %}" class="d-block float-right">Contact me</a>
  <p class="text-center ">copyright<span class="fa fa-copyright" aria-hidden="true"></span>{% now 'Y' %}</p>
</div>
{% endblock %}