articles/urls.py
from django.urls import path
from .views import (ArticleCreateView,ArticleListView,ArticleUpdateView,ArticleDeleteView, CustomLoginView,CustomListView,UserRegistration,contact_form_view,user_update_profile_view,article_detail, list_article_view,UserArticleView,likeview
)
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,

)
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

app_name = 'articles'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='articles:article-list'), name='logout'),
    path('register/',UserRegistration.as_view(),name='register'),
    path('',ArticleListView.as_view(), name='article-list'),
    path('user/<str:username>',UserArticleView.as_view(), name='user-article-list'),
    path('articles/tag/<slug:tag_slug>/',list_article_view, name='article-tag-list'),
    path('article/<int:pk>/detail/',article_detail, name='article-detail'),
    path('article/create/',ArticleCreateView.as_view(), name='article-create'),
    path('article/<int:pk>/update/',ArticleUpdateView.as_view(), name='article-update'),
    path('article/<int:pk>/delete/',ArticleDeleteView.as_view(), name='article-delete'),
    path('articles/edit',CustomListView.as_view(), name='article-cutomize'),
    path('profile/<int:pk>/update/', user_update_profile_view, name='update-view'),
    path('like/<int:pk>',likeview, name='article-like'),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings
from articles.views import contact_form_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('articles.urls')),
    path('about/',contact_form_view, name='about-view'),
        path('password-reset/', auth_views.PasswordResetView.as_view(template_name='articles/password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='articles/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='articles/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='articles/password_reset_complete.html'), name='password_reset_complete'),
]


#  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) it is for cdn(for development)

templates/about.html
{% extends 'layout.html' %} {% block title %}
<title>About page</title>
{% endblock %} {% block content %} {% if message_name %}
<center>
  <h3 class="text-success">Thanks {{message_name}} for your feedback</h3>
  <p>your message has been sent to us.</p>
</center>
{% else %}
<div class="row">
  <div class="col-lg-6 mt-4">
    <p>
      This website is created for developers and everyone who interested in
      technology.
      <br />Also,people can share and post their thoughts and expriences to
      anyone.
    </p>
    <address>
      If you had any questions or critics and suggestions feel free to contact
      us via this form or through social media:
      <a
        href="https://www.linkedin.com/in/pouya-pargam-1917b6218"
        class="fa fa-linkedin"
      ></a>
      <a href="https://www.instagram.com/pouyap19" class="fa fa-instagram"></a>
    </address>
  </div>
  <div class="col-lg-6">
    <h3>Get in touch</h3>
    <form action="{% url 'about-view' %}" method="POST" class="form-group">
      {% csrf_token %}
      <div class="form-row mb-3">
        <div class="col-lg-6">
          <label for="name" class="">Enter your name:</label>
          <input
            type="text"
            name="message-name"
            id="name"
            class="form-control"
            placeholder="Your name"
          />
        </div>
        <div class="col-lg-6">
          <label for="mail" class="">Enter your email:</label>
          <input
            type="email"
            name="message-email"
            id="mail"
            class="form-control"
            placeholder="example@gmail.com"
          />
        </div>
      </div>
      <div class="form-row">
        <div class="col-lg-12">
          <textarea
            name="message-content"
            id="msg"
            cols="75"
            rows="10"
            placeholder="your message"
            class="form-control mb-2"
          ></textarea>
          <input
            type="submit"
            id="send_mail"
            value="Send"
            class="btn btn-lg btn-primary"
          />
        </div>
      </div>
    </form>
  </div>
</div>

<br /><br />
{% endif %} {% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
    <title>layout</title>
    {% endblock %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/layout.css' %}"
    />
  </head>
  <body>
    <div class="navbar-container">
      <nav class="navbar navbar-expand-lg bg-dark navbar-dark fixed-top">
        <a class="navbar-brand" href="{% url 'articles:article-list' %}">Logo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a
                href="{% url 'articles:article-list' %}"
                class="nav-link text-white"
                >Home</a
              >
            </li>
            <li class="nav-item active">
              <a href="{% url 'about-view' %}" class="nav-link text-white"
                >About</a
              >
            </li>
          </ul>
        <ul class="navbar-nav ml-auto">
          {% if not request.user.is_authenticated %}
          <li class="nav-item login">
            <a href="{% url 'articles:login' %}" class="nav-link text-white"
              >Login/Register</a
            >
          </li>
          {% else %}

          <!-- dropdown -->

          <li class="nav-item logout dropdown ml-auto">
            <a
              href="#"
              class="nav-link dropdown-toggle text-white"
              data-toggle="dropdown"
            >
              {{request.user.username}}</a
            >
            <div class="dropdown-menu dropdown-menu-right text-white">
              <a
                href="{% url 'articles:update-view' pk=request.user.pk %}"
                class="dropdown-item"
                >profile</a
              >
              <a
                href="{% url 'articles:article-cutomize' %}"
                class="dropdown-item"
                >Your posts</a
              >
              <div class="dropdown-divider"></div>
              <a href="{% url 'articles:logout' %}" class="dropdown-item"
                >Logout</a
              >
            </div>
          </li>
        </ul>
        </div>
         

        {% endif %}
      </nav>
      {% block jumbotron %}
    </div>
    <div class="jumbotron mt-0">
      <h1>Create and share your thoughts</h1>
      <p>
        Feel free to read and write articles about technology and web
        development.
      </p>
    </div>
    {% endblock %}
    <div class="container mt-3">{% block content %} {% endblock %}</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
      integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/pagination.html
<div class="container">
    <div class="pagination">
        <span class="step-links">
            {% if page.has_previous %}
            <a href="?page=1">first</a><span> |</span>
            <a href="?page={{ page_obj.previous_page_number }}">previous |</a>
            {% endif %}
            <span class="current">
                page {{ page.number }} of {{ page.paginator.num_pages }}
            </span>
            {% if page.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">| next</a>
            <span> | </span><a href="?page={{ page_obj.paginator.num_pages }}">last</a>
            {% endif %}
        </span>
    </div>
</div>